//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IcalCreator.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BD_SICYPROHEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BD_SICYPROHEntities object using the connection string found in the 'BD_SICYPROHEntities' section of the application configuration file.
        /// </summary>
        public BD_SICYPROHEntities() : base("name=BD_SICYPROHEntities", "BD_SICYPROHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BD_SICYPROHEntities object.
        /// </summary>
        public BD_SICYPROHEntities(string connectionString) : base(connectionString, "BD_SICYPROHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BD_SICYPROHEntities object.
        /// </summary>
        public BD_SICYPROHEntities(EntityConnection connection) : base(connection, "BD_SICYPROHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iEpisodio">No Metadata Documentation available.</param>
        public ObjectResult<ppGenerarEventoAgenda_Result> ppGenerarEventoAgenda(Nullable<global::System.Int32> iEpisodio)
        {
            ObjectParameter iEpisodioParameter;
            if (iEpisodio.HasValue)
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", iEpisodio);
            }
            else
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<ppGenerarEventoAgenda_Result>("ppGenerarEventoAgenda", iEpisodioParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iEpisodio">No Metadata Documentation available.</param>
        public ObjectResult<ppObtenerAsistentesAgenda_Result> ppObtenerAsistentesAgenda(Nullable<global::System.Int32> iEpisodio)
        {
            ObjectParameter iEpisodioParameter;
            if (iEpisodio.HasValue)
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", iEpisodio);
            }
            else
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<ppObtenerAsistentesAgenda_Result>("ppObtenerAsistentesAgenda", iEpisodioParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iFolioEvento">No Metadata Documentation available.</param>
        /// <param name="iTipoEvento">No Metadata Documentation available.</param>
        public int ppRegistrarEventoAgenda(Nullable<global::System.Int32> iFolioEvento, Nullable<global::System.Int32> iTipoEvento)
        {
            ObjectParameter iFolioEventoParameter;
            if (iFolioEvento.HasValue)
            {
                iFolioEventoParameter = new ObjectParameter("iFolioEvento", iFolioEvento);
            }
            else
            {
                iFolioEventoParameter = new ObjectParameter("iFolioEvento", typeof(global::System.Int32));
            }
    
            ObjectParameter iTipoEventoParameter;
            if (iTipoEvento.HasValue)
            {
                iTipoEventoParameter = new ObjectParameter("iTipoEvento", iTipoEvento);
            }
            else
            {
                iTipoEventoParameter = new ObjectParameter("iTipoEvento", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("ppRegistrarEventoAgenda", iFolioEventoParameter, iTipoEventoParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ppObtenerCirugiasPrograAgenda_Result> ppObtenerCirugiasPrograAgenda()
        {
            return base.ExecuteFunction<ppObtenerCirugiasPrograAgenda_Result>("ppObtenerCirugiasPrograAgenda");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ppObtenerCitaMedicaAgenda_Result> ppObtenerCitaMedicaAgenda()
        {
            return base.ExecuteFunction<ppObtenerCitaMedicaAgenda_Result>("ppObtenerCitaMedicaAgenda");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iEpisodio">No Metadata Documentation available.</param>
        public ObjectResult<ppGenerarEventoAgendaCita_Result> ppGenerarEventoAgendaCita(Nullable<global::System.Int32> iEpisodio)
        {
            ObjectParameter iEpisodioParameter;
            if (iEpisodio.HasValue)
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", iEpisodio);
            }
            else
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<ppGenerarEventoAgendaCita_Result>("ppGenerarEventoAgendaCita", iEpisodioParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iEpisodio">No Metadata Documentation available.</param>
        public ObjectResult<ppObtenerAsistentesCitaAgenda_Result> ppObtenerAsistentesCitaAgenda(Nullable<global::System.Int32> iEpisodio)
        {
            ObjectParameter iEpisodioParameter;
            if (iEpisodio.HasValue)
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", iEpisodio);
            }
            else
            {
                iEpisodioParameter = new ObjectParameter("iEpisodio", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<ppObtenerAsistentesCitaAgenda_Result>("ppObtenerAsistentesCitaAgenda", iEpisodioParameter);
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_SICYPROHModel", Name="ppGenerarEventoAgenda_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ppGenerarEventoAgenda_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iFolioEvento
        {
            get
            {
                return _iFolioEvento;
            }
            set
            {
                OniFolioEventoChanging(value);
                ReportPropertyChanging("iFolioEvento");
                _iFolioEvento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iFolioEvento");
                OniFolioEventoChanged();
            }
        }
        private Nullable<global::System.Int32> _iFolioEvento;
        partial void OniFolioEventoChanging(Nullable<global::System.Int32> value);
        partial void OniFolioEventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtFechaInicio
        {
            get
            {
                return _dtFechaInicio;
            }
            set
            {
                OndtFechaInicioChanging(value);
                ReportPropertyChanging("dtFechaInicio");
                _dtFechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtFechaInicio");
                OndtFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtFechaInicio;
        partial void OndtFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OndtFechaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtFechaFin
        {
            get
            {
                return _dtFechaFin;
            }
            set
            {
                OndtFechaFinChanging(value);
                ReportPropertyChanging("dtFechaFin");
                _dtFechaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtFechaFin");
                OndtFechaFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtFechaFin;
        partial void OndtFechaFinChanging(Nullable<global::System.DateTime> value);
        partial void OndtFechaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchUbicacion
        {
            get
            {
                return _vchUbicacion;
            }
            set
            {
                OnvchUbicacionChanging(value);
                ReportPropertyChanging("vchUbicacion");
                _vchUbicacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchUbicacion");
                OnvchUbicacionChanged();
            }
        }
        private global::System.String _vchUbicacion;
        partial void OnvchUbicacionChanging(global::System.String value);
        partial void OnvchUbicacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchDescripcion
        {
            get
            {
                return _vchDescripcion;
            }
            set
            {
                OnvchDescripcionChanging(value);
                ReportPropertyChanging("vchDescripcion");
                _vchDescripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchDescripcion");
                OnvchDescripcionChanged();
            }
        }
        private global::System.String _vchDescripcion;
        partial void OnvchDescripcionChanging(global::System.String value);
        partial void OnvchDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchResumen
        {
            get
            {
                return _vchResumen;
            }
            set
            {
                OnvchResumenChanging(value);
                ReportPropertyChanging("vchResumen");
                _vchResumen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchResumen");
                OnvchResumenChanged();
            }
        }
        private global::System.String _vchResumen;
        partial void OnvchResumenChanging(global::System.String value);
        partial void OnvchResumenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchNombreOrganizador
        {
            get
            {
                return _vchNombreOrganizador;
            }
            set
            {
                OnvchNombreOrganizadorChanging(value);
                ReportPropertyChanging("vchNombreOrganizador");
                _vchNombreOrganizador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchNombreOrganizador");
                OnvchNombreOrganizadorChanged();
            }
        }
        private global::System.String _vchNombreOrganizador;
        partial void OnvchNombreOrganizadorChanging(global::System.String value);
        partial void OnvchNombreOrganizadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchCorreoOrganizador
        {
            get
            {
                return _vchCorreoOrganizador;
            }
            set
            {
                OnvchCorreoOrganizadorChanging(value);
                ReportPropertyChanging("vchCorreoOrganizador");
                _vchCorreoOrganizador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchCorreoOrganizador");
                OnvchCorreoOrganizadorChanged();
            }
        }
        private global::System.String _vchCorreoOrganizador;
        partial void OnvchCorreoOrganizadorChanging(global::System.String value);
        partial void OnvchCorreoOrganizadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchResumenAlerta
        {
            get
            {
                return _vchResumenAlerta;
            }
            set
            {
                OnvchResumenAlertaChanging(value);
                ReportPropertyChanging("vchResumenAlerta");
                _vchResumenAlerta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchResumenAlerta");
                OnvchResumenAlertaChanged();
            }
        }
        private global::System.String _vchResumenAlerta;
        partial void OnvchResumenAlertaChanging(global::System.String value);
        partial void OnvchResumenAlertaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_SICYPROHModel", Name="ppGenerarEventoAgendaCita_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ppGenerarEventoAgendaCita_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iFolioEvento
        {
            get
            {
                return _iFolioEvento;
            }
            set
            {
                OniFolioEventoChanging(value);
                ReportPropertyChanging("iFolioEvento");
                _iFolioEvento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iFolioEvento");
                OniFolioEventoChanged();
            }
        }
        private Nullable<global::System.Int32> _iFolioEvento;
        partial void OniFolioEventoChanging(Nullable<global::System.Int32> value);
        partial void OniFolioEventoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtFechaInicio
        {
            get
            {
                return _dtFechaInicio;
            }
            set
            {
                OndtFechaInicioChanging(value);
                ReportPropertyChanging("dtFechaInicio");
                _dtFechaInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtFechaInicio");
                OndtFechaInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtFechaInicio;
        partial void OndtFechaInicioChanging(Nullable<global::System.DateTime> value);
        partial void OndtFechaInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dtFechaFin
        {
            get
            {
                return _dtFechaFin;
            }
            set
            {
                OndtFechaFinChanging(value);
                ReportPropertyChanging("dtFechaFin");
                _dtFechaFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtFechaFin");
                OndtFechaFinChanged();
            }
        }
        private Nullable<global::System.DateTime> _dtFechaFin;
        partial void OndtFechaFinChanging(Nullable<global::System.DateTime> value);
        partial void OndtFechaFinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchUbicacion
        {
            get
            {
                return _vchUbicacion;
            }
            set
            {
                OnvchUbicacionChanging(value);
                ReportPropertyChanging("vchUbicacion");
                _vchUbicacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchUbicacion");
                OnvchUbicacionChanged();
            }
        }
        private global::System.String _vchUbicacion;
        partial void OnvchUbicacionChanging(global::System.String value);
        partial void OnvchUbicacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchDescripcion
        {
            get
            {
                return _vchDescripcion;
            }
            set
            {
                OnvchDescripcionChanging(value);
                ReportPropertyChanging("vchDescripcion");
                _vchDescripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchDescripcion");
                OnvchDescripcionChanged();
            }
        }
        private global::System.String _vchDescripcion;
        partial void OnvchDescripcionChanging(global::System.String value);
        partial void OnvchDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchResumen
        {
            get
            {
                return _vchResumen;
            }
            set
            {
                OnvchResumenChanging(value);
                ReportPropertyChanging("vchResumen");
                _vchResumen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchResumen");
                OnvchResumenChanged();
            }
        }
        private global::System.String _vchResumen;
        partial void OnvchResumenChanging(global::System.String value);
        partial void OnvchResumenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchNombreOrganizador
        {
            get
            {
                return _vchNombreOrganizador;
            }
            set
            {
                OnvchNombreOrganizadorChanging(value);
                ReportPropertyChanging("vchNombreOrganizador");
                _vchNombreOrganizador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchNombreOrganizador");
                OnvchNombreOrganizadorChanged();
            }
        }
        private global::System.String _vchNombreOrganizador;
        partial void OnvchNombreOrganizadorChanging(global::System.String value);
        partial void OnvchNombreOrganizadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchCorreoOrganizador
        {
            get
            {
                return _vchCorreoOrganizador;
            }
            set
            {
                OnvchCorreoOrganizadorChanging(value);
                ReportPropertyChanging("vchCorreoOrganizador");
                _vchCorreoOrganizador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchCorreoOrganizador");
                OnvchCorreoOrganizadorChanged();
            }
        }
        private global::System.String _vchCorreoOrganizador;
        partial void OnvchCorreoOrganizadorChanging(global::System.String value);
        partial void OnvchCorreoOrganizadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchResumenAlerta
        {
            get
            {
                return _vchResumenAlerta;
            }
            set
            {
                OnvchResumenAlertaChanging(value);
                ReportPropertyChanging("vchResumenAlerta");
                _vchResumenAlerta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchResumenAlerta");
                OnvchResumenAlertaChanged();
            }
        }
        private global::System.String _vchResumenAlerta;
        partial void OnvchResumenAlertaChanging(global::System.String value);
        partial void OnvchResumenAlertaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_SICYPROHModel", Name="ppObtenerAsistentesAgenda_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ppObtenerAsistentesAgenda_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchNombre
        {
            get
            {
                return _vchNombre;
            }
            set
            {
                OnvchNombreChanging(value);
                ReportPropertyChanging("vchNombre");
                _vchNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchNombre");
                OnvchNombreChanged();
            }
        }
        private global::System.String _vchNombre;
        partial void OnvchNombreChanging(global::System.String value);
        partial void OnvchNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchCorreo
        {
            get
            {
                return _vchCorreo;
            }
            set
            {
                OnvchCorreoChanging(value);
                ReportPropertyChanging("vchCorreo");
                _vchCorreo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchCorreo");
                OnvchCorreoChanged();
            }
        }
        private global::System.String _vchCorreo;
        partial void OnvchCorreoChanging(global::System.String value);
        partial void OnvchCorreoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iEstadoParticipación
        {
            get
            {
                return _iEstadoParticipación;
            }
            set
            {
                OniEstadoParticipaciónChanging(value);
                ReportPropertyChanging("iEstadoParticipación");
                _iEstadoParticipación = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iEstadoParticipación");
                OniEstadoParticipaciónChanged();
            }
        }
        private Nullable<global::System.Int32> _iEstadoParticipación;
        partial void OniEstadoParticipaciónChanging(Nullable<global::System.Int32> value);
        partial void OniEstadoParticipaciónChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iRsvp
        {
            get
            {
                return _iRsvp;
            }
            set
            {
                OniRsvpChanging(value);
                ReportPropertyChanging("iRsvp");
                _iRsvp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iRsvp");
                OniRsvpChanged();
            }
        }
        private Nullable<global::System.Int32> _iRsvp;
        partial void OniRsvpChanging(Nullable<global::System.Int32> value);
        partial void OniRsvpChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_SICYPROHModel", Name="ppObtenerAsistentesCitaAgenda_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ppObtenerAsistentesCitaAgenda_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iIdUsuario
        {
            get
            {
                return _iIdUsuario;
            }
            set
            {
                OniIdUsuarioChanging(value);
                ReportPropertyChanging("iIdUsuario");
                _iIdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iIdUsuario");
                OniIdUsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _iIdUsuario;
        partial void OniIdUsuarioChanging(Nullable<global::System.Int32> value);
        partial void OniIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchNombre
        {
            get
            {
                return _vchNombre;
            }
            set
            {
                OnvchNombreChanging(value);
                ReportPropertyChanging("vchNombre");
                _vchNombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchNombre");
                OnvchNombreChanged();
            }
        }
        private global::System.String _vchNombre;
        partial void OnvchNombreChanging(global::System.String value);
        partial void OnvchNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vchCorreo
        {
            get
            {
                return _vchCorreo;
            }
            set
            {
                OnvchCorreoChanging(value);
                ReportPropertyChanging("vchCorreo");
                _vchCorreo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vchCorreo");
                OnvchCorreoChanged();
            }
        }
        private global::System.String _vchCorreo;
        partial void OnvchCorreoChanging(global::System.String value);
        partial void OnvchCorreoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iEstadoParticipación
        {
            get
            {
                return _iEstadoParticipación;
            }
            set
            {
                OniEstadoParticipaciónChanging(value);
                ReportPropertyChanging("iEstadoParticipación");
                _iEstadoParticipación = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iEstadoParticipación");
                OniEstadoParticipaciónChanged();
            }
        }
        private Nullable<global::System.Int32> _iEstadoParticipación;
        partial void OniEstadoParticipaciónChanging(Nullable<global::System.Int32> value);
        partial void OniEstadoParticipaciónChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iRsvp
        {
            get
            {
                return _iRsvp;
            }
            set
            {
                OniRsvpChanging(value);
                ReportPropertyChanging("iRsvp");
                _iRsvp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iRsvp");
                OniRsvpChanged();
            }
        }
        private Nullable<global::System.Int32> _iRsvp;
        partial void OniRsvpChanging(Nullable<global::System.Int32> value);
        partial void OniRsvpChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_SICYPROHModel", Name="ppObtenerCirugiasPrograAgenda_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ppObtenerCirugiasPrograAgenda_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iCodCirugia
        {
            get
            {
                return _iCodCirugia;
            }
            set
            {
                OniCodCirugiaChanging(value);
                ReportPropertyChanging("iCodCirugia");
                _iCodCirugia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iCodCirugia");
                OniCodCirugiaChanged();
            }
        }
        private Nullable<global::System.Int32> _iCodCirugia;
        partial void OniCodCirugiaChanging(Nullable<global::System.Int32> value);
        partial void OniCodCirugiaChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="BD_SICYPROHModel", Name="ppObtenerCitaMedicaAgenda_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ppObtenerCitaMedicaAgenda_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> iCodCita
        {
            get
            {
                return _iCodCita;
            }
            set
            {
                OniCodCitaChanging(value);
                ReportPropertyChanging("iCodCita");
                _iCodCita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("iCodCita");
                OniCodCitaChanged();
            }
        }
        private Nullable<global::System.Int32> _iCodCita;
        partial void OniCodCitaChanging(Nullable<global::System.Int32> value);
        partial void OniCodCitaChanged();

        #endregion

    }

    #endregion

    
}
